### ISSUE TITLE
上传有bug

### ISSUE THREAD

**Issue by vip68** [crawlab-team/crawlab-sdk#23]
版本0.6.0-3

1、当环境为Windows时，使用upload命令上传，实际上传的路径变成/xxx/xxx\xxx\xxx这种形式，上传上能成功，但是传上去都成同一级
2、当环境为Mac时，使用命令upload .命令上传当前路径的文件，上传能成功，但最终所有的文件名都被删除了“.”（例如scrapy.cfg，上传后变成了scrapycfg）

**Comment by tikazyq** [comment]
我需要复测一下
