### ISSUE TITLE
save_items方法，在运行一段时间后，保存不到数据库。

### ISSUE THREAD

**Issue by luo-geng** [crawlab-team/crawlab-sdk#28]
版本：0.6.1
刚开始是好的，设置定时任务后，过几天看结果，发现任务有数量记录，但是点进去看不到任务的结果，去数据库看也没有新增，开启了url去重过滤

**Comment by luo-geng** [comment]
是python的sdk

**Comment by tikazyq** [comment]
最新版本还存在这样的问题吗？

**Comment by luo-geng** [comment]
> 最新版本还存在这样的问题吗？

还没升级,最后另改了个数据库名字,又好了
