### ISSUE TITLE
【增强】Crawlab 容器镜像里升级 requests 和 scrapy 时遇到兼容性报错问题

### ISSUE THREAD

**Issue by Zerorigin** [crawlab-team/crawlab-sdk#4]
ERROR crawlab-sdk 0.1.7 has requirement requests==2.22.0, but you'll have requests 2.24.0 which is incompatible.
ERROR crawlab-sdk 0.1.7 has requirement scrapy==1.8.0, but you'll have scrapy 2.2.0 which is incompatible.

也许该升级下 SDK 了？

**Comment by zkqiang** [comment]
最新版已升级

**Comment by nieweiming** [comment]
你好，是否能将crawlab-sdk对scrapy的版本要求修改为scrapy >= 2.2.0；
不然scrapy升级后会一直出现兼容性问题。
当前scrapy最新版本为2.4.1；
